name: Cops And Robbers by Deranged Senators
version: "3.0"
summary: CopsAndRobbers Unity Game
description: |
  A Multiplayer Cops And Robbers Game written in Unity
base: core18
confinement: strict

parts:
  unity-game:
    after: [desktop-gtk2]
    plugin: dump
    source: snap/local/gamefiles
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwebp6
  desktop-gtk2:
    build-packages:
      - build-essential
      - libgtk2.0-dev
    make-parameters:
      - FLAVOR=gtk2
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
      - ibus-gtk
      - libibus-1.0-5

apps:
  mygame:
    command: desktop-launch $SNAP/CopsAndRobbers.x86_64
    environment:
      LD_LIBRARY_PATH: "$SNAP/CopsAndRobbers_Data/Plugins/x86_64:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
    plugs:
      - x11
      - opengl
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - pulseaudio
      - joystick
